### ISSUE TITLE
when and unless

### ISSUE THREAD

**Issue by andys8** [Chadtech/elm-bool-extra#7]
Hi @Chadtech :wave: 

I'm missing `when` and `unless`. Basically helpers that do nothing in the default case and and apply a function in a when the condition holds.

`(a → Boolean) → (a → a) → a → a`

https://ramdajs.com/docs/#unless
https://ramdajs.com/docs/#when

Implementation would probably look something like this. Do you think this would be good fit for this library?

```elm
when : (a -> Bool) -> (a -> a) -> a -> a
when pred f a =
    if pred a then
        f a

    else
        a

unless : (a -> Bool) -> (a -> a) -> a -> a
unless pred f a =
    when (pred >> not) f a
```

**Comment by Chadtech** [comment]
Hey @andys8 !

Do you have any examples of when this could be useful? I just searched my current project for `    if`, and 16 results came up, but none of them seem to fit the form of using one input for the condition, and then only wanting to modify that input.

**Comment by andys8** [comment]
Hey, so the focus is that there is no real else case. There can be a variant of type `(Bool) -> (a -> a) -> a -> a` (and both could be part of this library), but it can be implemented with `when` and `always` in the condition.

Or what do you think about one with a default case: `(a -> Bool) -> (a -> b) -> b -> a -> b`?

**Comment by Chadtech** [comment]
I'm not really sure.

Well you said you were missing those from Ramda. It sounded like you would use these functions. What does using `when` look like in practice?

**Comment by andys8** [comment]
Hey, when I use `if else then` expressions in Elm I've the feeling it would be less verbose, if there would be helper's like they exist in Ramda. I'm not using them because there is no library, it doesn't make sense to extract a single helper or they're splitted over other libraries by type (`maybe-extra`, `list-extra` ...). I plan to look go and extract some helpers and look if they would fit into this library. Feel free to close this issue.

**Comment by andys8** [comment]
I stumbled on a case that might be related to initial ideas (but not matching `when`/`unless`). I'm adding it as example for discussion, but it's not that this is a case where readability would be improved ..

```
    ifElse
        (Ok str)
        (Err ( "Mail not valid", [] ))
        (Regex.contains regex str)
```

It would match the `(a -> Bool) -> (a -> b) -> b -> a -> b` case:


```
    applyIf
        (Regex.contains regex)
        (Ok)
        (Err ( "Mail not valid", [] ))
```

**Comment by Chadtech** [comment]
I think I am going to close this one. I appreciate opening the issue and talking it through @andys8 , but I think a helper like this just isnt useful enough. I see the benefit of a pipe-able if statement, but, it doesnt outweigh the cons of lost readability and the overhead of having an extra helper.

**Comment by andys8** [comment]
👍
