### ISSUE TITLE
LICENSE does not contain BSD-3 license as indicated in elm.json

### ISSUE THREAD

**Issue by rlefevre** [Chadtech/elm-bool-extra#9]
[elm.json](https://github.com/Chadtech/elm-bool-extra/blob/93a0952b23055565afd24f69c2447c0a997dddb3/elm.json#L5) indicates a BSD-3 license, but the [`LICENSE`](https://github.com/Chadtech/elm-bool-extra/blob/93a0952b23055565afd24f69c2447c0a997dddb3/LICENSE#L1) file actually contains:

> You can use this software

**Comment by Chadtech** [comment]
Thank you! I will fix this soon.

**Comment by Chadtech** [comment]
It is done.

**Comment by rlefevre** [comment]
Thank you. 

I'm really sorry to nitpick, but the new one seems to me to be incomplete. It is almost a 0BSD or ISC license, but the copyright and above all the actual permission to use the software seems to be missing.  There is only the non liability clause. Is it on purpose?

**Comment by Chadtech** [comment]
Oh sorry! No you are not nitpicking. I screwed up. I will fix it.

**Comment by Chadtech** [comment]
Okay. I think I got it. Thanks again @rlefevre !
